### ISSUE TITLE
Weekly Dashboard

### ISSUE THREAD

**Issue by limichange** [OneKeyHQ/portal#122]
⛳️ This is a list of what we will be working on this week.

## DONE

- [x] https://github.com/OneKeyHQ/portal/issues/109
- [x] https://github.com/OneKeyHQ/portal/issues/124
- [x] https://github.com/OneKeyHQ/portal/issues/145
- [x] https://github.com/OneKeyHQ/portal/issues/84
- [x] https://github.com/OneKeyHQ/portal/issues/130
- [x] https://github.com/OneKeyHQ/portal/issues/123

## TODO

- [ ] https://github.com/OneKeyHQ/portal/issues/127
- [ ] https://github.com/OneKeyHQ/portal/issues/103
- [ ] https://github.com/OneKeyHQ/portal/issues/104
- [ ] https://github.com/OneKeyHQ/portal/issues/128
